spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
   hibernate:
     ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
   show-sql: true
   database: postgresql
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   open-in-view: false
   generate-ddl: true